### ISSUE TITLE
Getting KeyError from container attributes probe on passed in network name

### ISSUE THREAD

**Issue by auramix** [gtmanfred/teststack#28]
Getting a key error after commit https://github.com/gtmanfred/teststack/commit/ad19f5b9bccf3461b9a38fd717de24b990379397

> `(acsbp-3515-1)dependency-analyzer % teststack exec
> 
> Traceback (most recent call last):
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/bin/teststack", line 8, in <module>
>     sys.exit(main())
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/teststack/__init__.py", line 144, in main
>     cli()
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
>     rv.append(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/teststack/commands/containers.py", line 344, in exec
>     container = ctx.invoke(start)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/teststack/commands/containers.py", line 94, in start
>     env = ctx.invoke(cli.get_command(ctx, 'env'), prefix=prefix, inside=True, no_export=True, quiet=True)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/teststack/commands/environment.py", line 73, in env
>     container_data = client.get_container_data(name, network=ctx.obj['project_name'], inside=inside)
>   File "/Users/josephs/.pyenv/versions/3.9.0/envs/dep_analyzer3.9/lib/python3.9/site-packages/teststack/containers/docker.py", line 199, in get_container_data
>     data['HOST'] = container.attrs['NetworkSettings']['Networks'][network]['IPAddress'] if inside else 'localhost'
> KeyError: 'dependency-analyzer'`

**Comment by auramix** [comment]
I ran `teststack restart` and tried to reproduce it but couldn't. Closing.
